#ifndef SHARED_MEMORY_H
#define SHARED_MEMORY_H

#define BAYCAPACITYPERTYPESIZE (3 * sizeof(int))
#define BUSTYPESIZE (4 * sizeof(char))
#define BAYSIZE (4 * sizeof(char))

#define BAYCAPACITYPERTYPEOFFSET (0)
#define BUSTYPEOFFSET (BAYCAPACITYPERTYPEOFFSET + BAYCAPACITYPERTYPESIZE)
#define BAYOFFSET (BUSTYPEOFFSET + BUSTYPESIZE)

#define SHAREDMEMORYSIZE (BAYCAPACITYPERTYPESIZE + BUSTYPESIZE + BAYSIZE)

void * attachToSharedMemory(int);

#endif
